apiVersion: apps/v1  
kind: Deployment
metadata:
  name: nodeserver
  labels:
    app: nodeserver   
spec:                            
  selector:
    matchLabels:
      app: nodeserver
  replicas: 1
  template:
    metadata:         
      labels:
        app: "nodeserver"
    spec:
      containers:
        - name: "nodeserver"
          image: "venilson/hello-node:latest"
          resources:
            limits:
              cpu: 400m
              memory: 400Mi
            requests:
              cpu: 100m
              memory: 100Mi